
'use client';

import { AlertTriangle, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 space-y-12">
      <Link href="/">
        <Button variant="ghost" className="rounded-full gap-2 mb-8">
          <ArrowLeft size={18} /> Back to Garden
        </Button>
      </Link>

      <div className="glass rounded-[3rem] p-12 space-y-8 border-white/40">
        <div className="flex items-center gap-6">
          <div className="p-5 rounded-3xl bg-amber-100 text-amber-600">
            <AlertTriangle size={48} />
          </div>
          <h1 className="text-5xl font-black gradient-text">Disclaimer</h1>
        </div>

        <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-muted-foreground font-medium">
          <p className="text-xl italic">Read carefully before exploring the garden.</p>
          
          <section className="space-y-4">
            <h2 className="text-2xl font-black text-foreground">AI Generated Content</h2>
            <p>The messages generated by AI Cupid are created using artificial intelligence. While we strive for heartfelt content, we are not responsible for how these messages are received or the outcome of their use in your relationships.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-black text-foreground">Personal Use Only</h2>
            <p>LoveGurden is intended for personal and recreational use. The advice and quotes provided are for inspirational purposes only and should not replace professional relationship advice.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-black text-foreground">External Links</h2>
            <p>Our WhatsApp contact and social sharing features are external services. Use them at your own discretion and according to their respective terms of service.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
    